spring:
  application:
    name: security
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}
      config:
        failFast: false
        format: yaml